targets:
  $default:
    sources:
      - lib/**
      - graphql/**
    builders:
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - "type=lint"
      artemis:
        options:
          fragments_glob: graphql/**.fragment.graphql
          scalar_mapping:
            - graphql_type: Date
              dart_type: DateTime
            - graphql_type: DateTime
              dart_type: DateTime
            - graphql_type: GitTimestamp
              dart_type: DateTime
            - graphql_type: PreciseDateTime
              dart_type: DateTime
            - graphql_type: X509Certificate
              dart_type: DateTime
            - graphql_type: GitRefname
              dart_type: DateTime
            - graphql_type: HTML
              dart_type: String
            - graphql_type: DeclineTopicSuggestionInput
              dart_type: String
            - graphql_type: GitObjectID
              dart_type: String
            - graphql_type: GitSignature
              dart_type: String
            - graphql_type: URI
              dart_type: Uri
          schema_mapping:
            - schema: graphql/schema.docs.graphql
              queries_glob: graphql/queries/**.query.graphql
              output: lib/graphql/graphql.dart
              naming_scheme: pathedWithFields
          ignore_for_file:
            - "type=lint"
