name: diohub
description: A Github mobile client

publish_to: 'none'

version: 1.0.0-dev.2+5

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  animated_theme_switcher:
    path: ../animated_theme_switcher
  animations: ^2.0.11
  another_flushbar: ^1.12.30
  app_links: ^6.3.3
  auto_route: ^9.2.2
  built_value: ^8.9.3
  cached_network_image: ^3.4.1
  chucker_flutter: ^1.8.2
  connectivity_plus: ^6.1.1
  curl_logger_dio_interceptor: ^1.0.0
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.1
  # https://github.com/tekartik/sqflite/issues/1008
  # When fixed, remove the change in ios/Podfile
  dio_cache_interceptor_db_store: ^5.1.1
  dynamic_color: ^1.7.0
  dynamic_sliver_app_bar:
    path: dependencies/dynamic_sliver_app_bar
  equatable: ^2.0.7
  expand_widget: ^3.1.1

  # Modified to remove the current typing word indicator.
  extended_text_field:
    path:
      dependencies/extended_text_field
  ferry_flutter: ^0.9.1-dev.1
  flex_list: ^1.0.0
  flutter:
    sdk: flutter

  flutter_appauth: ^8.0.3
  flutter_bloc: ^8.1.6
  flutter_colorpicker: ^1.1.0
  flutter_countdown_timer: ^4.1.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_displaymode: ^0.6.0

  flutter_dynamic_tabs:
    path: dependencies/flutter_dynamic_tabs

  flutter_emoji: ^2.5.1

  # Modified to add background color option.
  flutter_highlighting:
    path:
      dependencies/dart-highlighting/flutter_highlighting

  # Temporary dependency until the following is fixed: https://github.com/pichillilorenzo/flutter_inappwebview/issues/1735#issuecomment-1725248033
  flutter_inappwebview: ^6.1.5

  flutter_keyboard_visibility: ^6.0.0
  flutter_material_design_icons: ^1.1.7447
  flutter_portal: ^1.1.4
  flutter_reaction_button: ^3.0.0+3
  flutter_riverpod: ^2.6.1
  flutter_scroll_to_top:
    path: dependencies/flutter_scroll_to_top

  flutter_secure_storage: ^9.2.2
  flutter_slidable: ^3.1.2
  flutter_svg: ^2.0.16
  flutter_vector_icons: ^2.0.0
  flutter_widget_from_html: ^0.15.3
  #  google_nav_bar: ^5.0.6
  freezed: ^2.5.7
  gql: ^1.0.1-alpha+1730759315362
  gql_dio_link: ^1.0.2-alpha+1709845491515
  gql_exec: ^1.0.1-alpha+1709845491450
  #  gql_link: ^1.0.0

  #  highlighting:
  #    path: dependencies/dart-highlighting/highlighting

  html: ^0.15.5
  image_stack: ^2.1.1
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.20.1
  #  json_annotation: ^4.8.1
  #  line_icons: ^2.0.3
  logger: ^2.5.0
  markdown: ^7.2.2

  # Modified for additional markdown options.
  markdown_editable_textinput:
    path: dependencies/markdown-editable-textinput

  mime: ^2.0.0
  package_info_plus: ^8.1.2
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  pull_down_button:
    path: dependencies/pull_down_button
  share_plus: ^10.1.3
  shared_preferences: ^2.3.4
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  sqlite3_flutter_libs: ^0.5.27
  #  tabbed_view: ^1.18.0
  #  super_context_menu: ^0.9.0-dev.5
  timeline_tile: ^2.0.0
  #  uni_links: ^0.5.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.14
  # pub run dependency_validator
  dependency_validator: ^4.1.2
  ferry_generator: ^0.12.0-dev.0+1
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  melos: ^6.2.0

#dependency_overrides:
# Override for conflict between artemis and flutter_test.
#  collection: ^1.18.0
# flutter_html 2.1.2 uses a version not compatible with flutter >3.
#  flutter_layout_grid: ^2.0.4
#  flutter_math_fork: ^0.7.1
#  flutter_svg: ^2.0.7
# Override until https://github.com/comigor/artemis/pull/415 is merged.
#  gql_link: 1.0.0
# chucker_flutter incompatibility.
#  share_plus: ^7.2.0

flutter_native_splash:
  color: '#17181c'
  image: assets/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope/Manrope-ExtraLight.ttf
          weight: 200
        - asset: fonts/Manrope/Manrope-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/Manrope/Manrope-Light.ttf
          weight: 300
        - asset: fonts/Manrope/Manrope-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Manrope/Manrope-Regular.ttf
          weight: 400
        - asset: fonts/Manrope/Manrope-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Manrope/Manrope-Medium.ttf
          weight: 500
        - asset: fonts/Manrope/Manrope-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: fonts/Manrope/Manrope-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Manrope/Manrope-Bold.ttf
          weight: 700
        - asset: fonts/Manrope/Manrope-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Manrope/Manrope-ExtraBold.ttf
          weight: 800
        - asset: fonts/Manrope/Manrope-ExtraBoldItalic.ttf
          style: italic
          weight: 800
    #    - family: AtkinsonHyperlegible
    #      fonts:
    #        - asset: fonts/AtkinsonHyperlegible/Atkinson-Hyperlegible-Regular.ttf
    #          weight: 400
    #        - asset: fonts/AtkinsonHyperlegible/Atkinson-Hyperlegible-Italic.ttf
    #          style: italic
    #          weight: 400
    #        - asset: fonts/AtkinsonHyperlegible/Atkinson-Hyperlegible-Bold.ttf
    #          weight: 700
    #        - asset: fonts/AtkinsonHyperlegible/Atkinson-Hyperlegible-BoldItalic.ttf
    #          style: italic
    #          weight: 700
    - family: OpenDyslexic3
      fonts:
        - asset: fonts/OpenDyslexic3/OpenDyslexic3-Regular.ttf
          weight: 400
        - asset: fonts/OpenDyslexic3/OpenDyslexic3-Bold.ttf
          weight: 700

flutter_launcher_icons:
  #  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  background_color_ios: "#17181c"

#  min_sdk_android: 21
#  web:
#    generate: true
#    image_path: "assets/logo.png"
#    background_color: "#17181c"
#    theme_color: "#17181c"
#  windows:
#    generate: true
#    image_path: "assets/logo.png"
#    icon_size: 48 # min:48, max:256, default: 48
#  macos:
#    generate: true
#    image_path: "assets/logo.png"
